### PR TITLE
add GetVersion

### PR DESCRIPTION
**Pull request by MrOutput**
http://stackoverflow.com/questions/41541370/how-to-provide-regular-variable-to-scope-resolution-operator

### CODE REVIEW

**Comment by jamesiarmes** [comment]
What's your motivation for this? Looking at the examples in your link, you're trying to read the variable off the class and not the object, but since the property is not static and won't be defined until an instance of the client is instantiated, this won't help you.

**Comment by MrOutput** [comment]
that's actually NOT my question; I explained that in the comment I left on that post... who cares what the motivation is, if someone wants to read the version off the client instance, they should be able to, why hide it?

**Comment by RobinvdA** [comment]
@jamesiarmes is right. If I understand the question on SO correctly, 'Alex G' asking for a way to access a const using a variable name, which (imo) is not something this class is responsible for.

**Comment by MrOutput** [comment]
The OP edited his question many times since I replied and therefore his intentions weren't as clear. I agree his intention is not reasonable. It looked like he had a Client instance and was trying to get the version from it but couldn't since it was protected.

However being that he is constructing client's with different versions based on user input, it is reasonable to add such a method so this information can persist in a database. What is your reasoning for NOT exposing a method that return the version information?

**Comment by jamesiarmes** [comment]
I'm not opposed to adding it, but I want to know why any code is necessary before I merge it. This goes for a simple getter just as it would a new type implementation. The version is set on the client (unless the default is used) either via the constructor or the setter method, so the developer has to have access to this value in order to do so. Why would they then need to read it off the client when they already have it from elsewhere?

**Pull request closed without merging**
