### PR TITLE
fix bald xml characters from ms exchange

### PR DESCRIPTION
**Pull request by prolic**
see: https://github.com/jamesiarmes/php-ews/issues/223

### CODE REVIEW

**Comment by prolic** [comment]
ping @jamesiarmes

**Comment by mrnnn** [comment]
@jamesiarmes, can we have this merged (or fixed in any other way you see fit)? We are running into this issue as well.

**Comment by jamesiarmes** [comment]
Sorry it's taken me so long to get to this, can somebody give me an example request that would produce this issue?

**Comment by jamesiarmes** [comment]
See associated issue (#223) for the resolution to this issue.

**Pull request closed without merging**
