### PR TITLE
Add composer file

### PR DESCRIPTION
**Pull request by martintern**
Added a composer.json file. Not sure if the license is correct.
Also added a branch-alias to make it easier to get the latest dev version.

When merged, you do need to register this on packagist.

Thanks!

### CODE REVIEW

**Comment by prolic** [comment]
ping @jamesiarmes

**Comment by DarkAxi0m** [comment]
ping @jamesiarmes

**Comment by mariendev** [comment]
ping @jamesiarmes

**Comment by nvanheuverzwijn** [comment]
Is @jamesiarmes still even alive ?

**Comment by prolic** [comment]
Who likes to work on it, fork it and Register on packagist. Just take over
the project.
Even if james comes back one time, we can reintegrate or he moves his repo
to new owner.
Am 21.04.2016 02:15 schrieb "Nicolas Vanheuverzwijn" <
notifications@github.com>:

**Comment by jamesiarmes** [comment]
I'm still alive, I promise! I've been working on moving the classes into a more organized structure before making an official composer release, you can see my progress in the psr-4 branch. In the meantime, there is a package on packagist that points at the composer branch, which was originally a fork created by someone else: https://packagist.org/packages/php-ews/php-ews. It's a few commits behind master, but any patches are welcome.

**Comment by nvanheuverzwijn** [comment]
Glad to hear from you @jamesiarmes 
Have you seen [this repo](https://github.com/Garethp/php-ews) ? The guy made like 350 more commits.
Some improvement have been made notably in reusing existing exchange connection.

Regards,

**Comment by jamesiarmes** [comment]
This has been added in the [psr-4](https://github.com/jamesiarmes/php-ews/tree/psr-4) branch.

**Pull request closed without merging**
